language: python
os: linux
dist: focal
sudo: false
python: "3.5"

script:
  # cmake install script code from:
  # https://github.com/ldionne/mpl11/blob/master/.travis.yml
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade python3
    fi
  - cd ${TRAVIS_BUILD_DIR}
  - $CXX --version
  - python3 --version
  - ./test.py all


# testing matrix
# somewhat stolen from https://github.com/taocpp/PEGTL/blob/master/.travis.yml
# and from here https://stackoverflow.com/questions/29312015/building-with-more-than-one-version-of-a-compiler
matrix:
  include:
    # osx -----------------------------------------------------------------------------------------------------
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      compiler: clang
      env:
        - CXX=clang++

    # gcc -----------------------------------------------------------------------------------------------------
    - compiler: gcc
      env:
        - CXX=g++-4.8

    # clang --------------------------------------------------------------------------------------------------

    # catch2 doesnt suppor this...
    #- dist: precise
    #  compiler: clang
    #  env:
    #    - CXX=clang++

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.5']
      env:
        - CXX=clang++-3.5
