language: python
os: linux
dist: trusty
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - $CXX --version
  - python3 --version
  - ./test.py all


# testing matrix
# somewhat stolen from https://github.com/taocpp/PEGTL/blob/master/.travis.yml
# and from here https://stackoverflow.com/questions/29312015/building-with-more-than-one-version-of-a-compiler
matrix:
  include:
    # gcc -----------------------------------------------------------------------------------------------------
    - compiler: gcc
      env:
        - CXX=g++-4.8

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX=g++-4.9

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5

    # clang --------------------------------------------------------------------------------------------------

    - dist: precise
      compiler: clang
      env:
        - CXX=clang++
    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.5']
      env:
        - CXX=clang++-3.5

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.6']
      env:
        - CXX=clang++-3.6
