language: cpp

compiler: clang

script:
   - python3 --version
   - ./test.py all

dist: trusty

sudo: false

addons:
  apt:
    update: true
    sources:
    - deadsnakes
    packages:
    - python3.7

# https://github.com/travis-ci/travis-ci/issues/3668#issuecomment-279276549
install:
   - mkdir -p latest-symlinks
   - ln -s /usr/bin/python3.7 latest-symlinks/python3
   - export PATH=$PWD/latest-symlinks:$PATH
