language: cpp
dist: focal
sudo: false

script:
  - $CXX --version
  - cmake --version
  - python3 --version
  - ./test.py all


matrix:
  include:
    # osx -----------------------------------------------------------------------------------------------------
    - os: osx
      osx_image: xcode12u
      compiler: clang
      env:
        - CXX=clang++

    # gcc -----------------------------------------------------------------------------------------------------
    - os: linux
      compiler: gcc
      env:
        - CXX=g++-9
        - CC=gcc-9

    # clang --------------------------------------------------------------------------------------------------
    - os: linux
      compiler: clang
