language: cpp
compiler: clang
script:
   - pwd
   - which python3
   - which python
   - python --version
   - ./test-all.py
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5